server:
  port: 8090

togli:
  base-url: http://localhost:8080
  api-key: hft_JRpTlQR_PEPihD4sDEycV2QyPfFAoK4vK30zKqykyGM
  project-slug: EXAMPLE
  default-environment: DEV
  service-name: togli-example-app_2
  namespace: prod
  # namespace: production  # optional, uncomment for Kubernetes
