var QUOTES = [
  'Born because someone pushed to main on Friday',
  'Toggle first, ask questions later',
  'Your on-call engineer will finally sleep',
  'Cheaper than therapy for your DevOps team',
  "We don't judge your 11 PM deploys. We just make them safe",
  "Bugtracker ticket to remove a banner? That's 3 sprints. Or one toggle",
  'Your product owner just mass-toggled 12 flags. Nobody died',
  "Every \"temporary if-statement\" is permanent. You know it. We know it",
  "Microservices, monolith, spaghetti code \u2014 we don't judge, we just toggle",
  'So your PM can finally turn things off without a Jira ticket',
  "No more \"it's behind an if-statement in production\"",
  'Somewhere a PM is writing a 40-page release plan. You just need one click',
  'Your QA found 12 bugs. You toggled off 12 features',
  'Your frontend deploys 400MB of JavaScript. But disabling a feature still requires a new build. Think about that',
  "\"I'll just hardcode it for now and fix it later.\" \u2014 a developer, 2 years ago. It's still hardcoded",
  "\"We don't need feature flags, we have git branches.\" \u2014 someone who mass-resolves merge conflicts every Monday",
  "Your codebase has a folder called /utils/feature_flags/legacy/v2_final_FINAL. Nobody knows what's inside",
  'Your PM booked a 2-hour "release planning" meeting. The release took 2 seconds. The meeting still happened',
  'Designer wants dark mode for 10% of users. Frontend wants to go home',
  'You mass-commented 400 lines of code to disable a feature. Git diff looks like a crime scene',
];
